### ISSUE TITLE
Required minimum Android Gradle Plugin version 7.1

### ISSUE THREAD

**Issue by nksaroj** [2BAB/Polyfill#9]
Worth removing the max check as it's breaking with higer versions

https://github.com/2BAB/Polyfill/blob/cdc783cd8292b2cb828beb0221f5b2907696501c/polyfill/src/main/kotlin/me/xx2bab/polyfill/PolyfillPlugin.kt#L64

**Comment by 2BAB** [comment]
Good idea. I think I can change it to a warning log that a higher AGP version is detected and it's not tested with the current Polyfill. Hopefully, I can make it along with AGP 7.4/8.0 next month.

**Comment by nksaroj** [comment]
I can raise PR if you want and can release quickly

**Comment by 2BAB** [comment]
PR is welcome, will help with the following ci check and release.

**Comment by nksaroj** [comment]
@2BAB https://github.com/2BAB/Polyfill/pull/10 is here for your approval.

**Comment by nksaroj** [comment]
@2BAB Do you know when it would be merged?

**Comment by 2BAB** [comment]
Hi, @nksaroj I would merge and release by this evening (UTC+8).

**Comment by nksaroj** [comment]
Thanks I am waiting so I can pull for my work.. I need the  bundle-tool-gradle-plugin But it seems that has the dependency on Polyfill.

**Comment by 2BAB** [comment]
Released, it reflects on maven central already. https://repo1.maven.org/maven2/me/2bab/polyfill/0.8.1/
